[package]
name = "polyhedron_game_server"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = "0.3"
tokio = { version = "1", features = ["full"] }
arrayvec = "0.7"
clap = { version = "4", features = ["derive"] }
